# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Fpy ====================

Fpy:
  - FpyEmulator
  - Emulator
  - Error
  - Optimization

FpyHeartbeat:
  - Scheduler
  - FpyInterval

# ==================== FpyFarm ====================

FpyMain:
  - Scheduler
  - FpyTeam
  - FpyApple
  - FpyLimit
  - FpyInterval

# ==================== FpyDaily ====================

FpyDailyFpSummon:
  - Scheduler

# ==================== Tool ====================

FpyBattle: []

FpyBenchmark:
  - FpyBenchmark

FpyCall:
  - FpyCall
